name: Compile Firmware

on:
  push:
    branches:
    - main

jobs:
  Build:
    runs-on: ubuntu-latest

    container: d3xter93/sonix_base_container

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Clone main repository
      run: git clone https://github.com/SonixQMK/qmk_firmware.git
    - name: Change main repository branch to configured build branch
      run: cd qmk_firmware && git checkout `cat ../BUILD_BRANCH | tr -d '\r' | tr -d '\n'`
    - name: Pull in main repository submodules
      run: cd qmk_firmware && make git-submodule
    - name: Install rsync
      run: apt-get update && apt-get install --no-install-recommends -y rsync
    - name: Copy keymaps
      run: ls -lah && rsync -a keyboards/ qmk_firmware/keyboards/
    - name: Copy build script
      run: cp build.py qmk_firmware/lib/python/build.py
    - name: Copy whitelist
      run: cp KEYBOARD_LIST qmk_firmware/WHITELIST
    - name: Install dependencies
      run: cd qmk_firmware && pip3 install -r requirements.txt
    - name: Build Sonix keyboards
      run:  cd qmk_firmware && python3 lib/python/build.py --debug --whitelist WHITELIST
    - name: Declare some variables
      id: vars
      shell: bash
      run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF_NAME//\//-})"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: Pre-Compiled Firmware (${{ steps.vars.outputs.branch }}-${{ steps.vars.outputs.sha_short }})
        path: 'qmk_firmware/*.bin'
        
    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: Pre-Compiled Firmware
        path: 'qmk_firmware/*.bin'
